const channelsData = [
  {
    id: 1,
    name: "Tech Talks",
    description: "Discuss the latest in technology and gadgets.",
    profilePicture: "https://picsum.photos/seed/tech/150",
    lastMessage: "Have you tried the new iPhone update?",
    timestamp: "10:30 AM",
    membersCount: 150,
    unreadCount: 5,
  },
  {
    id: 2,
    name: "Gaming Hub",
    description: "Join for gaming tips and live streams!",
    profilePicture: "https://picsum.photos/seed/gaming/150",
    lastMessage: "Who's up for a CS:GO session tonight?",
    timestamp: "09:15 AM",
    membersCount: 300,
    unreadCount: 12,
  },
  {
    id: 3,
    name: "Movie Buffs",
    description: "All about movies, series, and cinema!",
    profilePicture: "https://picsum.photos/seed/movies/150",
    lastMessage: "The new Marvel movie trailer is amazing!",
    timestamp: "Yesterday",
    membersCount: 500,
    unreadCount: 0,
  },
  {
    id: 4,
    name: "Fitness Freaks",
    description: "Daily workout tips and motivation.",
    profilePicture: "https://picsum.photos/seed/fitness/150",
    lastMessage: "Here’s a new yoga routine to try out.",
    timestamp: "2:45 PM",
    membersCount: 200,
    unreadCount: 2,
  },
  {
    id: 5,
    name: "Travel Diaries",
    description: "Share your travel experiences and tips.",
    profilePicture: "https://picsum.photos/seed/travel/150",
    lastMessage: "Check out my new blog on Iceland adventures!",
    timestamp: "Monday",
    membersCount: 75,
    unreadCount: 7,
  },
  {
    id: 6,
    name: "Food Lovers",
    description: "Recipes, food pics, and restaurant reviews.",
    profilePicture: "https://picsum.photos/seed/food/150",
    lastMessage: "Anyone tried making homemade pasta?",
    timestamp: "Sunday",
    membersCount: 230,
    unreadCount: 0,
  },
  {
    id: 7,
    name: "Coding Ninjas",
    description: "Help and resources for developers.",
    profilePicture: "https://picsum.photos/seed/coding/150",
    lastMessage: "Here's a great GitHub repo for learning React!",
    timestamp: "11:00 AM",
    membersCount: 400,
    unreadCount: 3,
  },
  {
    id: 8,
    name: "Crypto Enthusiasts",
    description: "News and updates on cryptocurrency.",
    profilePicture: "https://picsum.photos/seed/crypto/150",
    lastMessage: "Bitcoin prices are on the rise again!",
    timestamp: "Yesterday",
    membersCount: 1000,
    unreadCount: 15,
  },
  {
    id: 9,
    name: "Book Club",
    description: "Read and discuss great books together.",
    profilePicture: "https://picsum.photos/seed/books/150",
    lastMessage: "Any recommendations for mystery novels?",
    timestamp: "Monday",
    membersCount: 120,
    unreadCount: 0,
  },
  {
    id: 10,
    name: "Photography Enthusiasts",
    description: "Share your photos and get feedback.",
    profilePicture: "https://picsum.photos/seed/photography/150",
    lastMessage: "Check out this photo I took at sunrise!",
    timestamp: "Sunday",
    membersCount: 180,
    unreadCount: 4,
  },
];

export default channelsData;
