const chatListData = [
  {
    id: 1,
    name: "John Doe",
    profilePicture: "https://picsum.photos/seed/john/150",
    lastMessage: "Hey, how are you?",
    timestamp: "10:45 AM",
    unreadCount: 20,
  },
  {
    id: 2,
    name: "Jane Smith",
    profilePicture: "https://picsum.photos/seed/jane/150",
    lastMessage: "Let's catch up later!",
    timestamp: "09:30 AM",
    unreadCount: 0,
  },
  {
    id: 3,
    name: "Michael Brown",
    profilePicture: "https://picsum.photos/seed/michael/150",
    lastMessage: "Did you get the report?",
    timestamp: "Yesterday",
    unreadCount: 1,
  },
  {
    id: 4,
    name: "Emily Davis",
    profilePicture: "https://picsum.photos/seed/emily/150",
    lastMessage: "Thanks for the help!",
    timestamp: "2:15 PM",
    unreadCount: 0,
  },
  {
    id: 5,
    name: "Chris Wilson",
    profilePicture: "https://picsum.photos/seed/chris/150",
    lastMessage: "Meeting at 3 PM, don't forget.",
    timestamp: "Monday",
    unreadCount: 3,
  },
  {
    id: 6,
    name: "Sophia Taylor",
    profilePicture: "https://picsum.photos/seed/sophia/150",
    lastMessage: "Great job on the project!",
    timestamp: "Sunday",
    unreadCount: 0,
  },
  {
    id: 7,
    name: "Daniel Anderson",
    profilePicture: "https://picsum.photos/seed/daniel/150",
    lastMessage: "Call me when you’re free.",
    timestamp: "10:20 AM",
    unreadCount: 1,
  },
  {
    id: 8,
    name: "Olivia Martinez",
    profilePicture: "https://picsum.photos/seed/olivia/150",
    lastMessage: "Are you coming to the party?",
    timestamp: "Yesterday",
    unreadCount: 0,
  },
  {
    id: 9,
    name: "Liam Garcia",
    profilePicture: "https://picsum.photos/seed/liam/150",
    lastMessage: "Okay, got it!",
    timestamp: "Monday",
    unreadCount: 0,
  },
  {
    id: 10,
    name: "Ava Rodriguez",
    profilePicture: "https://picsum.photos/seed/ava/150",
    lastMessage: "See you soon!",
    timestamp: "Sunday",
    unreadCount: 2,
  },
  {
    id: 12,
    name: "Ava Rodriguez",
    profilePicture: "https://picsum.photos/seed/ava/150",
    lastMessage: "See you soon!",
    timestamp: "Sunday",
    unreadCount: 2,
  },
];

export default chatListData;
