const discoverChannelsData = [
  {
    id: 1,
    name: "Tech Innovators",
    category: "Technology",
    description: "Explore cutting-edge tech and innovation.",
    profilePicture: "https://picsum.photos/seed/techInnovators/150",
    followersCount: 1200,
    isFollowing: false,
  },
  {
    id: 2,
    name: "World Travelers",
    category: "Travel",
    description: "Discover hidden gems and travel hacks.",
    profilePicture: "https://picsum.photos/seed/worldTravelers/150",
    followersCount: 800,
    isFollowing: false,
  },
  {
    id: 3,
    name: "Gamer's Arena",
    category: "Gaming",
    description: "For gamers who live and breathe gaming.",
    profilePicture: "https://picsum.photos/seed/gamersArena/150",
    followersCount: 1500,
    isFollowing: true,
  },
  {
    id: 4,
    name: "Daily Motivation",
    category: "Lifestyle",
    description: "Stay motivated with daily quotes and tips.",
    profilePicture: "https://picsum.photos/seed/dailyMotivation/150",
    followersCount: 500,
    isFollowing: false,
  },
  {
    id: 5,
    name: "Crypto Gurus",
    category: "Finance",
    description: "Your guide to cryptocurrency and blockchain.",
    profilePicture: "https://picsum.photos/seed/cryptoGurus/150",
    followersCount: 2000,
    isFollowing: false,
  },
  {
    id: 6,
    name: "Foodie's Paradise",
    category: "Food",
    description: "Recipes, reviews, and all things food.",
    profilePicture: "https://picsum.photos/seed/foodiesParadise/150",
    followersCount: 1100,
    isFollowing: true,
  },
  {
    id: 7,
    name: "Fitness Squad",
    category: "Health & Fitness",
    description: "Join us for workouts, tips, and more.",
    profilePicture: "https://picsum.photos/seed/fitnessSquad/150",
    followersCount: 700,
    isFollowing: false,
  },
  {
    id: 8,
    name: "Movie Maniacs",
    category: "Entertainment",
    description: "Discuss movies, series, and entertainment news.",
    profilePicture: "https://picsum.photos/seed/movieManiacs/150",
    followersCount: 900,
    isFollowing: false,
  },
  {
    id: 9,
    name: "Bookworms United",
    category: "Books",
    description: "For those who love to read and share books.",
    profilePicture: "https://picsum.photos/seed/bookwormsUnited/150",
    followersCount: 600,
    isFollowing: false,
  },
  {
    id: 10,
    name: "Code Masters",
    category: "Programming",
    description: "Learn coding, share projects, and get help.",
    profilePicture: "https://picsum.photos/seed/codeMasters/150",
    followersCount: 1800,
    isFollowing: true,
  },
];

export default discoverChannelsData;
